services:
  shuttled:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    ports:
      - "443:443/tcp"
      - "443:443/udp"
    volumes:
      - shuttle-config:/etc/shuttle
    environment:
      - SHUTTLE_DOMAIN=${SHUTTLE_DOMAIN:-}
      - SHUTTLE_PASSWORD=${SHUTTLE_PASSWORD:-}
    restart: unless-stopped

volumes:
  shuttle-config:
